package Challenges.wordsearch;

import javax.swing.*;
import java.awt.*;

public class CongratulationWindow extends JFrame {
  private JPanel contentPanel;
  private JButton button;
  private JLabel message;
  private JLabel title;
  private JLabel message2;


  public CongratulationWindow(WordSearch game) {
    setSize(700, 400);
    setContentPane(contentPanel);

    button.addActionListener(e -> {
      this.dispose();
      game.dispose();
    });
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPanel = new JPanel();
    contentPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
    contentPanel.setBackground(new Color(-3348993));
    button = new JButton();
    button.setText("Continue");
    contentPanel.add(button, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    message = new JLabel();
  //  Font messageFont = this.$$$getFont$$$("Helvetica", -1, 24, message.getFont());
  //  if (messageFont != null) message.setFont(messageFont);
    message.setForeground(new Color(-14471362));
    message.setText("You have now completed the challenge!");
    contentPanel.add(message, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    title = new JLabel();
    //Font titleFont = this.$$$getFont$$$("Helvetica", Font.BOLD, 36, title.getFont());
  //  if (titleFont != null) title.setFont(titleFont);
    title.setForeground(new Color(-14471362));
    title.setText("Congratulations!");
    contentPanel.add(title, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    message2 = new JLabel();
   // Font message2Font = this.$$$getFont$$$("Helvetica", -1, 24, message2.getFont());
  //  if (message2Font != null) message2.setFont(message2Font);
    message2.setForeground(new Color(-14471362));
    message2.setHorizontalAlignment(0);
    message2.setHorizontalTextPosition(0);
    message2.setText("Please click the button below to continue.");
    contentPanel.add(message2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
 /* private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
  } */

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPanel;
  }
}
