package Challenges.wordsearch;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class WordList extends JPanel {

  private final Map<String, JCheckBox> map = new HashMap<>();
  private JPanel contentPanel;

  public WordList(ArrayList<String> words) {
    $$$setupUI$$$();
    for (String s : words) {
      JCheckBox box = new JCheckBox(s);
      box.setFont(new Font("Arial", Font.BOLD, 30));
      box.setEnabled(false);
      map.put(s, box);
      contentPanel.add(box);
    }
    this.setBackground(Color.decode("#CCE5FF"));
    this.add(contentPanel);
  }


  public void removeWord(String s) {
    remove(map.get(s));
    map.remove(s);
    WordSearch.currentGame.decreaseWordsLeft();
  }

  public boolean contains(String s) {
    return map.containsKey(s);
  }

  public Map<String, JCheckBox> getWordList() {
    return map;
  }

  public ArrayList<String> getWords() {
    return new ArrayList<>(map.keySet());
  }

  public void checkBox(String word) {
    JCheckBox checkBox = map.get(word);
    checkBox.setSelected(true);
  }

  private void createUIComponents() {
    contentPanel = new JPanel();
    contentPanel.setLayout(new GridLayout(0, 1));
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    contentPanel.setBackground(new Color(-3348993));
    contentPanel.setForeground(new Color(-3348993));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPanel;
  }
}
